// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzzfjzypjidbfptnibmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6emZqenlwamlkYmZwdG5pYm1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Nzk3NTIsImV4cCI6MjA2MjI1NTc1Mn0.wJfAnFwA1LHeywwrAtv88hGkRsLx-I0uvXG2-PNoxvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);